[package]
name = "bodex"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.3.2", default-features = false, features = ["std", "backend-winit", "backend-linuxkms", "renderer-femtovg", "renderer-skia", "renderer-skia-opengl", "renderer-skia-vulkan", "renderer-software", "compat-1-2"] }
rusqlite = { version = "0.29.0", features = ["bundled", "chrono"] }
chrono = "0.4"

[build-dependencies]
slint-build = "1.3.2"
