[package]
name = "bodex"
version = "0.1.0"
edition = "2021"

[dependencies]
# Limpiamos las features de Skia para evitar errores en Windows y agilizar la descarga
slint = { version = "1.3.2" }
rusqlite = { version = "0.29.0", features = ["bundled", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
bcrypt = "0.15"
lazy_static = "1.5.0"

[build-dependencies]
slint-build = "1.3.2"
