[env]
FORCE_SKIA_BINARIES_DOWNLOAD = "1"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-linux-android]
linker = "C:/Android/android-ndk-r27d/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android35-clang.cmd"

[target.armv7-linux-androideabi]
linker = "C:/Android/android-ndk-r27d/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi35-clang.cmd"
